### ISSUE TITLE
Multiproceso

### ISSUE THREAD

**Issue by Yusepi93** [rojoambinina/bitcoin-balance#3]
Como ejecutó el código en multiproceso soy novato

**Comment by rojoambinina** [comment]
> Como ejecutó el código en multiproceso soy novato

**Add these 2 lines above the code:**

import multiprocessing
from multiprocessing import Pool, Process, Queue

**Create 2 variables:**

counter = 0
cores = 9

**Create a finder function with the counter parameter and then add all the codes from the While loop in this function:**

def finder(counter):
global num_threads
LOG_EVERY_N = 500
start_time = dt.datetime.today().timestamp()
counts = 0
print("Core " + str(counter))

**For multiprocessing to work, you must put at the bottom of the code, that is to say after the Except part the following code:**

if __name__ == '__main__':
jobs = []
for counter in range(cores):
mandeha = multiprocessing.Process(target=finder, args=(counter,)) 
jobs.append(mandeha) mandeha.start() 

**_That's all_**

**Comment by Yusepi93** [comment]
Traceback (most recent call last):                           File "/root/Multi-Currency-Rich-Address-Finder-v1.0/bitcoin-bruteforce/BittyV3/Bittyblockstream.py", line 35, in <module>                                                          miz = ctypes.CDLL(pathdll)                                       ^^^^^^^^^^^^^^^^^^^^                               File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__                                                    self._handle = _dlopen(self._name, mode)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^               OSError: /root/Multi-Currency-Rich-Address-Finder-v1.0/bitcoin-bruteforce/BittyV3/ice_secp256k1.so: cannot open shared object file: No such file or directory.. da error

**Comment by Yusepi93** [comment]
Traceback (most recent call last):                           File "/root/Multi-Currency-Rich-Address-Finder-v1.0/bitcoin-bruteforce/BittyV3/Bittyblockstream.py", line 35, in <module>                                                          miz = ctypes.CDLL(pathdll)                                       ^^^^^^^^^^^^^^^^^^^^                               File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__                                                    self._handle = _dlopen(self._name, mode)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^               OSError: /root/Multi-Currency-Rich-Address-Finder-v1.0/bitcoin-bruteforce/BittyV3/ice_secp256k1.so: cannot open shared object file: No such file or directory
